# Generated by Django 4.0.1 on 2022-01-11 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Страна путешествия', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone_number', models.CharField(help_text='в формате +7ХХХХХХХХХХ', max_length=12)),
                ('user', models.OneToOneField(help_text='Клиент', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Дата изменения')),
                ('price', models.FloatField(help_text='Цена')),
                ('description', models.TextField(help_text='Описание предложения')),
                ('country', models.ForeignKey(help_text='Страна путевки', on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Дата изменения')),
                ('start_date', models.DateField(help_text='Дата начала путевки')),
                ('purchased_date', models.DateField(help_text='Дата покупки')),
                ('amount', models.FloatField(help_text='Сумма путевки')),
                ('hotel', models.CharField(help_text='Отель', max_length=100)),
                ('comment', models.CharField(help_text='Комментарий', max_length=100)),
                ('country', models.ForeignKey(help_text='Страна путевки', on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('customer', models.ForeignKey(help_text='Клиент', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Дата изменения')),
                ('pictrure', models.ImageField(upload_to='')),
                ('trip', models.ForeignKey(help_text='Путевка', on_delete=django.db.models.deletion.CASCADE, to='main.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
