# Generated by Django 4.0.1 on 2022-01-11 19:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='pictrure',
            field=models.ImageField(upload_to=main.models.trip_path),
        ),
    ]
