# Generated by Django 4.0.1 on 2022-01-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trip_name_alter_picture_pictrure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='picture',
            name='front_picture',
            field=models.BooleanField(default=False, help_text='Главная картинка'),
        ),
        migrations.AddField(
            model_name='trip',
            name='full_description',
            field=models.TextField(default='-', help_text='Полное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(help_text='Корткое описание предложения'),
        ),
    ]
