# Generated by Django 4.0.1 on 2022-01-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_trip_options_picture_front_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='pictrure',
            new_name='picture',
        ),
    ]
