# Generated by Django 4.0.1 on 2022-01-19 17:51

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, upload_to=main.models.trip_path),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mobile_phone_number',
            field=models.CharField(help_text='в формате 7ХХХХХХХХХХ', max_length=11),
        ),
    ]
