# Generated by Django 4.0.1 on 2022-01-20 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_picture_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='full_description',
        ),
        migrations.AddField(
            model_name='trip',
            name='beach',
            field=models.CharField(default='', help_text='Пляжная линия', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='trip',
            name='lat',
            field=models.FloatField(default=0, help_text='latitude'),
        ),
        migrations.AddField(
            model_name='trip',
            name='long',
            field=models.FloatField(default=0, help_text='longitude'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meal_type',
            field=models.CharField(default='', help_text='Тип питания', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='stars',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort', models.CharField(help_text='Курорт', max_length=100)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='resort',
            field=models.ForeignKey(help_text='Курорт', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resort'),
        ),
    ]
