# Generated by Django 4.0.1 on 2022-01-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_trip_duration_alter_trip_resort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='room_type',
            field=models.CharField(default='', help_text='Тип номера', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(help_text='Длительность тура'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='stars',
            field=models.IntegerField(default=-1, help_text='Звезды'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(help_text='Дата заезда'),
        ),
    ]
