# Generated by Django 4.0.1 on 2022-01-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_trip_room_type_alter_trip_duration_alter_trip_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='lat',
            field=models.FloatField(default=0, help_text='latitude', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='long',
            field=models.FloatField(default=0, help_text='longitude', null=True),
        ),
    ]
