# Generated by Django 4.0.1 on 2022-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_trip_lat_alter_trip_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
